### ISSUE TITLE
Distribute to External Testers option stopped working

### ISSUE THREAD

**Issue by 1Siger1** [microsoft/app-store-vsts-extension#192]
## Required Information
**Question, Bug, or Feature?**  
*Type*: Question or Bug

**Enter Task Name**: AppStoreRelease@1

## Environment
- Server - Azure Pipelines 
- Agent - Hosted MacOS-10.15

## Issue Description
From the start of November option for release to External testers stopped working. All testflight releases are not automatically released to External testers. What is strange the release logs shows information that everything is working as expected. Logs below:
    [2020-11-05 11:23:32.64]: Successfully finished processing the build **** for IOS
    [2020-11-05 11:23:33.10]: Successfully set the changelog for build
    [2020-11-05 11:23:33.30]: Distributing new build to testers: ****
    [2020-11-05 11:23:39.76]: Successfully distributed build to External testers 🚀
With this problem there is also additional warning - "You specified releaseNotes - so you need to provide fastlane session, app specific password only won't work". It started to show at the same time. I tried to solve it by adding fastlane session data to Apple App Store service connection in Azure DevOps, but it does not solve anything. The warning is logged even with this additional parameter added. What is strange the logs above shows information that the change log was set successfully for the build and when I look on the build in testflight the changelog is there. Does anyone have similar problem?

## Task logs
I can provide task logs in private.

**Comment by kitolog** [comment]
Same here

**Comment by egor-bryzgalov** [comment]
Hi @1Siger1  @kitolog 

Thank you for opening this issue! A fix was deployed. Please feel free to reopen the issue if you still face this problem.

**Comment by ekmobile** [comment]
@egor-bryzgalov we are still facing this issue with the message: "##[warning]You specified releaseNotes - so you need to provide fastlane session, app specific password only won't work".

We don't use external testers and use the App Store Connect API: https://docs.fastlane.tools/app-store-connect-api

Any idea why the release notes can't be submitted?

`[command]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane` pilot upload --api_key_path /Users/runner/work/_temp/api_key***.json -i /Users/runner/work/r1/a/...ipa --changelog Nothing new since last build`
