### ISSUE TITLE
Automatic task update broke our build pipelines because of increasing minimum agent version

### ISSUE THREAD

**Issue by omghb** [microsoft/app-store-vsts-extension#233]
## Note  

Because of the https://github.com/microsoft/app-store-vsts-extension/commit/43e071b0805a7f3629bed1a1c28bf1c32ab3160d
* bump minimum agent version

our build pipelines broke with following error:
`##[error]No agent found in pool OMICRON MAC which satisfies the following demand: Agent.Version. All demands: xcode, Xamarin.iOS, Agent.Version -gtVersion 2.182.1`

As Azure DevOps pipelines do not provide more information (e.g. missing info is about which Task is responsible for this demand) it took a lot time for us to track the issue down.

**Suggestion:** Please keep care with bumping minimum agent versions as you break a lot pipelines. The task was automatically updated so it made troubleshooting more difficult.

Maybe it is an option to bump the minimum agent version only by introducing a new task version.

## Required Information

**Bug**  

**Enter Task Name**:  ms-vsclient.app-store.app-store-release.AppStoreRelease@1

## Environment
- Server - Azure Pipelines or TFS on-premises?
    - If using TFS on-premises, provide the version: Latest (not sure about version number)
- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name: MAC with agent version : '2.170.1'

**Comment by anatolybolshakov** [comment]
Hi @omghb we don't consider minimum agent version bump as major task update - since service automatically updates agent version until this is not disabled, and we keep agent backward compatible between minor updates - so you can update agent also.

**Comment by omghb** [comment]
I believe that's not true for OnPremise versions. We use the latest Azure DevOps OnPremise: Version Dev18.M170.8

It downgraded our MAC build agent after we installed the latest agent version. This broke the build again. Therefore, it is necessary to disable "Allow agents in this pool to automatically update".

**Comment by ad-mca-mk** [comment]
I have sent a PR, which solved the issue locally for us.

**Comment by anatolybolshakov** [comment]
@ad-mca-mk did you try to update extension manually on on-prem version?

**Comment by ad-mca-mk** [comment]
Yup, the task is working locally and we've successfully published on 2 separate pipelines.

![image](https://user-images.githubusercontent.com/3054655/114169618-15e9f200-9932-11eb-8b56-ffced3bc6d26.png)

**Comment by anatolybolshakov** [comment]
@ad-mca-mk there was a new security feature introduced with last extension update which requires an agent of at least v2.182.1. It should be automatically updated for cloud product version, but please note that manual extension update for on premise solution could require further agents update.

**Comment by ad-mca-mk** [comment]
@anatolybolshakov How do we update on-prem agents since our AzureDevOpsServer 2020 does not get notified of the new agent releases? 

This is the image of a new agent creation dialog. So even our maintenance schedule does not update them to the latest version.
![image](https://user-images.githubusercontent.com/3054655/114204701-c6b7b780-9959-11eb-84ca-a904df7bb2c4.png)

**Comment by anatolybolshakov** [comment]
@ad-mca-mk you can upload the agent from release [page](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.184.2) - the one thing that you need to do is to set up 'AZP_AGENT_DOWNGRADE_DISABLED' to 'true' before agent configuration - to disable automatic agent downgrade to the default version for current on-premise.

**Comment by ad-mca-mk** [comment]
That is fine, since we have limited number of agents, but how would large organizations would manage it?
It does require a lot of manual work per agent.

(you can abandon the PR since it's a mandatory security requirement)

**Comment by scrthq** [comment]
This is also impacting us with our instance of Azure DevOps Server 2020.0.1 (latest stable). Our self-hosted macOS agents are on the latest version available for on-prem, which is 2.170.1 as @ad-mca-mk mentioned.

Is there a compatibility issue with the newer agent version from the release page and Azure DevOps Server 2020 or should we be fine pulling that zip so long as the environment variable is set to prevent automatic downgrade? 

Is there anything actually dependent for this task with agent version 2.182.0+ or is the specific version something that was just added arbitrarily since it is the latest agent version available after PR #220 from 7 days ago?

**Comment by anatolybolshakov** [comment]
@ad-mca-mk yes, closed it since there is security update - thanks anyway!
In general we suggest to be ready to update self-hosted agents used too - if there is extension update coming in.
@scrthq there should be backward compatibility for agent and previous Azure DevOps Server versions -  so it should be fine to pull last version for 2020.

**Comment by anatolybolshakov** [comment]
@omghb @ad-mca-mk @scrthq let me close this one since it looks resolved - please feel free to ask any further questions.

**Comment by scrthq** [comment]
@anatolybolshakov apologies for the late response here, didn't catch your reply 6 days ago. I'm still not understanding why the required version is a higher version than is currently available for on-prem without manually forcing the upgrade and blocking the automatic downgrade, vs just requiring the latest version of the agent that's available for Azure DevOps Server to ensure compatibility. Contrary to @ad-mca-mk , we are a large organization, so this isn't exactly a host that's incredibly accessible without building out automation to apply what is apparently a workaround without any explanation around why the task cannot support the latest on-prem version of the agent.

**Comment by scrthq** [comment]
My question in my comment 7 days ago wasn't asking whether the latest version of the agent is supported with Azure DevOps Server, you had answered that already when providing the workaround in the first place. I'm trying to understand why the minimum required version is higher than is available for on-prem Azure DevOps Server and why the workaround is needed vs allowing at least agent version 2.170.1.

This is the only extension that I've seen that establishes an agent version requirement higher than is available out of the box with the latest stable version of Azure DevOps Server. Any sort of context here around why the required version is what it is would be much appreciated, as it appears from the context available that the version requirement is arbitrarily based on the latest hosted agent version at the time.

**Comment by anatolybolshakov** [comment]
@scrthq there was security update on agent side introduced with [v2.182.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.182.1) - allowing to restrict variables which could be set by pipeline task - since new possible vector of attack was found related to some possible injection from untrusted tasks. We updated app store extension tasks to enable such restrictions and avoid such vulnerability.

**Comment by scrthq** [comment]
@anatolybolshakov Got it! Thank you for the clarification. I'm curious when Azure DevOps Server will be updating to that agent version.
