### ISSUE TITLE
Version 1.186.0 of the tasks requires a VSTS agent newer than what's available on Azure Devops On Prem 

### ISSUE THREAD

**Issue by Vinzz** [microsoft/app-store-vsts-extension#237]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: ms-vsclient.app-store.app-store-release.AppStoreRelease

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks/AppStoreRelease

## Environment
- Server - TFS on-premises?
    
    - If using TFS on-premises, provide the version: Azure DevOps Server 2020.0.1 Patch 2
 
- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    - Agent version : 2.170.1
    - OS version: Big Sure

## Issue Description
Last version from the task (1.186.0, deployed on the market place and installed on prem has a Minimum Agent Version set to  2.182.1, but this version of agents is not available yet on prem (we are stuck to 2.170.1 so far). 

Could you please lower this demand?

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

```##[error]No agent found in pool Default which satisfies the following demand: Agent.Version. All demands: Agent.Version -gtVersion 2.182.1

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by max-zaytsev** [comment]
Hi @Vinzz, there was a security update on the agent side introduced with [v2.182.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.182.1) - allowing to restrict variables which could be set by pipeline task - since a new possible vector of attack was found related to some possible injection from untrusted tasks. We updated app store extension tasks to enable such restrictions and avoid such vulnerability. 

To resolve your issue you can upload the agent from release [page](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.184.2) - the one thing that you need to do is to set up environment variable 'AZP_AGENT_DOWNGRADE_DISABLED' to 'true' before agent configuration - to disable automatic agent downgrade to the default version for current on-premise.

**Comment by Vinzz** [comment]
Hi @max-zaytsev, dutifully noted, but 2.182.1 agents won't work with ADS 2020.0.1 Patch 2 or so it seems.
It becomes the standard agent version with Update 1 though, it is still in RC2 but may come soon
Thanks for your answer, I'll wait for Update 1.

**Comment by max-zaytsev** [comment]
Hi @Vinzz,  2.182.1 agent should work after setting the environment variable 'AZP_AGENT_DOWNGRADE_DISABLED' to 'true' before agent configuration
