### ISSUE TITLE
App Store Connect API key content - always fails with [!] invalid curve name (OpenSSL::PKey::ECError)

### ISSUE THREAD

**Issue by brunck** [microsoft/app-store-vsts-extension#383]
I'm having the same issue as https://github.com/microsoft/app-store-vsts-extension/issues/218.

Using the Apple App Store release task, classic pipelines, and the App Store Connect API Key authentication method (key ID, issuer ID, key ID content, the latter as base64 encoded).

The .p8 file as downloaded from Apple has linebreaks after the BEGIN PRIVATE KEY and before the END PRIVATE KEY sections, and has linebreaks in the content itelf.

I removed the `0A` linebreaks in the content itself, as in the comment below.

I've done everything else listed in the comment as well, such as:

> > The error you're receiving is because the key is in the wrong format, so ruby cannot load it. The key should be of the format:
> > > -----BEGIN PRIVATE KEY-----\nxxxxxxxxxxxyyyyyyyyyyyzzzzzzzzaaaaaa\n-----END PRIVATE KEY----
> > 
> > 
> > The x, y, z, and a's are already the base64 content they are asking for. But the newlines do need to be escaped and the newlines in the key content should be removed for best results.
> 
> I removed the \n in between the x,y,z and a's and copied them in a single line. Also added \n only for first and last line, like: -----BEGIN PRIVATE KEY-----\nxxxxxxxxxxxyyyyyyyyyyyzzzzzzzzaaaaaa\n-----END PRIVATE KEY---- But got the same error.
> 
> Also tried without any \n, like: -----BEGIN PRIVATE KEY-----xxxxxxxxxxxyyyyyyyyyyyzzzzzzzzaaaaaa-----END PRIVATE KEY----, nothing is working.

I also base64-encoded each attempt using https://www.base64encode.org/, no luck.
I've also tried using a secure file and putting it into a pipeline variable, still the same result. I'm frustrated beyond belief at this point.

**Comment by brunck** [comment]
I had to:

1. Open the .p8 file
2. Copy the contents AS-IS
3. Use base64encode.org, default settings
4. Take the encoded string - and use in a pipeline variable, not in a secure file

**Comment by jasells** [comment]
Since I've been bouncing around several how-to's and finally ended up here, but some of the answers on #218  were still a _little_ unclear (to me) as to _how_ to convert the .p8 key file to base-64 correctly, I finally figured it out and wrote this little .ps script that works on any platform:

```
param ([string]$utfInput,
       [string]$b64out)

# read ALL content of the .p8 file downloaded from Apple, INCLUDING start/end tags!
$api_key_Str = Get-Content ./$utfInput;

$api_b64 = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($api_key_Str));

Write-Output "base64 encoded key, saved to $b64out--- ";
echo $api_b64;

#save to file
echo $api_b64 > $b64out;
```

The output string (NO LINE BREAKS!) can be saved as a secret pipeline var, input directly into a Service Connection, OR use this script in your pipeline to convert a securely-stored .p8 file inline each run.

One other note: setting “In House Enterprise” option to YES on my Service Connection was also giving me similar auth errors, even though I am using a company de account, so not sure what requires this setting.


Hope this helps some future frustrated engineer!
