### ISSUE TITLE
Unit tests will not pass using node 8.x

### ISSUE THREAD

**Issue by viperx77** [Microsoft/app-store-vsts-extension#94]
Unit tests that check the following will fail under node 8.x:

`assert(tr.stderr.length === 0, 'should not have written to stderr');`

As node 8.x has the following security warning:

` -(node:37380) Warning: Use Cipheriv for counter mode of aes-256-ctr`

See [this issue](https://github.com/valery-barysok/session-file-store/issues/65)

Fixed by settings environment variable NODE_NO_WARNINGS=1

Many of the unit tests should also be cleaned up to more correctly assert the condition such as:

`assert.equal(tr.stderr, '', 'should not have written to stderr');`

**Comment by lkillgore** [comment]
This needs to be fixed in Microsoft/vsts-task-lib#380.  We could disable the warnings, but it's better for us to know what they are to prevent any bugs from slipping through.

@viperx77, if you're blocked by this, I recommend downgrading to Node 6.x until we can update our library to support a later version of Node.  Thank you for letting us know about this issue.
