### ISSUE TITLE
SpecificVersion fails on 'uninstall fastlane' when no previous install version exists

### ISSUE THREAD

**Issue by jldeen** [Microsoft/app-store-vsts-extension#99]
Specific Version fails on 'uninstall fastlane' [Line 139](https://github.com/Microsoft/app-store-vsts-extension/blob/master/Tasks/app-store-release/app-store-release.ts#L139) when using hosted macOS agents since no previous version exists. 
![image001](https://user-images.githubusercontent.com/7676214/45901326-652d9e80-bd97-11e8-838f-1fd3dc239fa5.png)

**Comment by madhurig** [comment]
Fastlane is now installed on the Hosted macOS VMs, so we don't hit this error on the hosted VMs but it can happen on self hosted agents. The fix is now to attempt uninstall and warn in case of any errors since based on how the original gem was installed, the uninstall might need to be done differently via a custom script.

**Comment by madhurig** [comment]
Fix is merged and we will be doing a release tomorrow.
